[workspace]
members = ["apps/game", "crates/world"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
name = "bevy-worldbuilder"

[workspace.dependencies]
bevy = "0.16.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
rand = "0.8"
