[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["png"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
avian2d = { workspace = true }
bevy_ecs_tilemap = { workspace = true }

[build-dependencies]
builder = { path = "../../crates/builder" }
